services:
  docker:
    image: docker:27.1.1-dind
    container_name: docker
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - ./docker-certs:/certs/client
      - ./jenkins-data:/var/jenkins_home
    ports:
      - "2376:2376"    
    networks:
      - applications-network
    command: --storage-driver overlay2

  chillo-tech-jenkins:
    image: chillo-tech-jenkins:1.0.0
    container_name: chillo-tech-jenkins
    restart: on-failure
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    volumes:
      - ./jenkins-data:/var/jenkins_home
      - ./docker-certs:/certs/client:ro
    ports:
      - "9080:8080"
      - "50000:50000"
    networks:
      - applications-network

networks:
  applications-network:
    external: true
    name: applications-network
